resolver: lts-8.14
packages:
 - .
 - extra-dep: true
   location:
       git: https://github.com/haskell/deepseq
       commit: 0b22c9825ef79c1ee41d2f19e7c997f5cdc93494
 - extra-dep: true
   location:
       git: https://github.com/ekmett/semigroupoids.git
       commit: c3297f970658ae874db098190327ec742044a2e6
 - extra-dep: true
   location:
       git: http://github.com/ekmett/lens.git
       commit: 7031e00f62a704a86c3149c75c1e2afc059af022
 - extra-dep: true
   location:
       git: https://github.com/dreixel/syb.git
       commit: f584ecd525179778063df2eb02dc6bbe406d7e75
flags:
    tweet-hs:
        llvm-fast: true
        parallel-gc: false
ghc-options:
    tweet-hs: -fdiagnostics-color=always
allow-newer: true
compiler: ghc-8.2.0.20170507
compiler-check: match-exact
setup-info:
 ghc:
  linux64:
   8.2.0.20170507:
    url: https://downloads.haskell.org/~ghc/8.2.1-rc2/ghc-8.2.0.20170507-x86_64-deb8-linux.tar.xz
  macosx:
   8.2.0.20170507:
    url: https://downloads.haskell.org/~ghc/8.2.1-rc2/ghc-8.2.0.20170507-x86_64-apple-darwin.tar.xz
  windows64:
   8.2.0.20170507:
    url: https://downloads.haskell.org/~ghc/8.2.1-rc2/ghc-8.2.0.20170507-x86_64-unknown-mingw32.tar.xz
